### ISSUE TITLE
Stops processing when blank results are returned

### ISSUE THREAD

**Issue by novaksam** [logstash-plugins/logstash-filter-jdbc_streaming#14]
I'm using this filter to enhance reporting for suricata alerts, and I've recently discovered that when a blank result is returned, it appears to stop processing that particular event. Not sure if this is intended behavior, but if so, it could be beneficial to have a boolean that would allow the output variables to be set to, say, blank_result_returned when this happens.

**Comment by guyboertje** [comment]
This case is exactly what the `default_hash` is designed to cover.

[Docs](https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/blob/master/docs/index.asciidoc#plugins-filters-jdbc_streaming-default_hash) and tests - [setup](https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/blob/master/spec/filters/jdbc_streaming_spec.rb#L31) + [assertion](https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/blob/master/spec/filters/jdbc_streaming_spec.rb#L116)

**Comment by novaksam** [comment]
Goodness, that's embarrassing that I didn't see that.

Closing issue, thanks!
