### ISSUE TITLE
Parameter jdbc_password_filepath is missing

### ISSUE THREAD

**Issue by zwentastic** [logstash-plugins/logstash-filter-jdbc_streaming#29]
Please provide the parameter `jdbc_password_filepath` for storing the password in a separate file. 
This is necessary to separate secrets from configuration.

**Comment by robbavey** [comment]
@zwentastic Have you considered using the [Logstash Keystore](https://www.elastic.co/guide/en/logstash/current/keystore.html) to store your jdbc password?

**Comment by zwentastic** [comment]
@robbavey Thank you for this suggestion. I'm trying to use Logstash within a kubernetes environment. Therefore it would be more handy to use files for storing secrets. But using the Logstash Keystore might be a workaround.
