### ISSUE TITLE
TypeError: failed to coerce jdk.internal.loader.ClassLoaders$AppClassLoader to java.net.URLClassLoader

### ISSUE THREAD

**Issue by jguay** [logstash-plugins/logstash-filter-jdbc_streaming#34]
This is just to report/track that the same issue and same workaround solution on logstash 7.4.0 with jdbc_streaming filter plugin as for jdbc_static reported in https://github.com/logstash-plugins/logstash-filter-jdbc_static/issues/47

In this case issue occurred when using 
```
jdbc_streaming {
jdbc_driver_library => "/usr/share/logstash/x-pack-sql-jdbc-7.4.0.jar"
```

The same workaround solution worked - remove jdbc_driver_library setting or pass empty string and put the jar file directly in /usr/share/logstash/logstash-core/lib/jars/x-pack-sql-jdbc-7.4.0.jar

**Comment by Memento1990** [comment]
👍 It's very usefull for me. Thank you very much! 😄
